version: '3.1'

volumes:
  prysm:
    driver: local

services:
  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
    restart: always
    ports:
      - 4000:4000
    command:
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --http-web3provider=http://geth:8545
      - --accept-terms-of-use
    volumes:
      - prysm:/data
