# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eth/ext/options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='eth/ext/options.proto',
  package='ethereum.eth.ext',
  syntax='proto3',
  serialized_options=b'\n\024org.ethereum.eth.extB\014OptionsProtoP\001Z-github.com/prysmaticlabs/ethereumapis/eth/ext\252\002\020Ethereum.Eth.ext\312\002\020Ethereum\\Eth\\ext',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x65th/ext/options.proto\x12\x10\x65thereum.eth.ext\x1a google/protobuf/descriptor.proto:2\n\tcast_type\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\t:1\n\x08ssz_size\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\t:0\n\x07ssz_max\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\t:2\n\tspec_name\x12\x1d.google.protobuf.FieldOptions\x18\xd3\x86\x03 \x01(\tB{\n\x14org.ethereum.eth.extB\x0cOptionsProtoP\x01Z-github.com/prysmaticlabs/ethereumapis/eth/ext\xaa\x02\x10\x45thereum.Eth.ext\xca\x02\x10\x45thereum\\Eth\\extb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


CAST_TYPE_FIELD_NUMBER = 50000
cast_type = _descriptor.FieldDescriptor(
  name='cast_type', full_name='ethereum.eth.ext.cast_type', index=0,
  number=50000, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SSZ_SIZE_FIELD_NUMBER = 50001
ssz_size = _descriptor.FieldDescriptor(
  name='ssz_size', full_name='ethereum.eth.ext.ssz_size', index=1,
  number=50001, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SSZ_MAX_FIELD_NUMBER = 50002
ssz_max = _descriptor.FieldDescriptor(
  name='ssz_max', full_name='ethereum.eth.ext.ssz_max', index=2,
  number=50002, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
SPEC_NAME_FIELD_NUMBER = 50003
spec_name = _descriptor.FieldDescriptor(
  name='spec_name', full_name='ethereum.eth.ext.spec_name', index=3,
  number=50003, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=b"".decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.extensions_by_name['cast_type'] = cast_type
DESCRIPTOR.extensions_by_name['ssz_size'] = ssz_size
DESCRIPTOR.extensions_by_name['ssz_max'] = ssz_max
DESCRIPTOR.extensions_by_name['spec_name'] = spec_name
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(cast_type)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(ssz_size)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(ssz_max)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(spec_name)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
